---
- name: UploadToWinDeploymentRepos
  hosts: btk_db1 spb_emoiv omsk_emoiv habr_emoiv chel_emoiv oreh_emoiv zelec_mihi kna_mihi
  # hosts: omsk_emoiv
  tasks:
  # - name: Create directory structure
    # ansible.windows.win_file:
      # path: D:\deployment\filesharepath\tools
      # state: directory  
  - name: Copy a single file
    ansible.windows.win_copy:
      src: /tmp/SecurityMonitoring/SecurityChannelListener.zip
      dest: D:\deployment\filesharepath\tools\SecurityChannelListener.zip  